services:
  - type: web
    name: ai-meeting-summarizer
    env: python
    plan: free
    region: oregon  # or choose closest region
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
